// <auto-generated />
using System;
using LetterBoxdContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetterBoxdContext.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250611162706_fixedBrokenUrls")]
    partial class fixedBrokenUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetterBoxdDomain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("LetterBoxdDomain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A lone juror in a New York City murder trial refuses to convict without discussing the evidence, challenging the others to reexamine their assumptions and biases.",
                            ImageUrl = "https://media-cache.cinematerial.com/p/500x/c5whwpvz/12-angry-men-theatrical-movie-poster.jpg?v=1456708298",
                            ReleaseYear = 1957,
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A middle-school band teacher passionate about jazz journeys to a mysterious realm where he discovers the true meaning of life and soul.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZTZkYjA5MDEtMjY1ZC00ODk5LThjOTUtZDYxODEzYWNjMTU2XkEyXkFqcGc@._V1_.jpg",
                            ReleaseYear = 2020,
                            Title = "Soul"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTc3MDcwMTc1MV5BMl5BanBnXkFtZTcwMzk4NTU3Mg@@._V1_.jpg",
                            ReleaseYear = 2009,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/The-Godfather-1082x1536.jpg",
                            ReleaseYear = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A thief who steals corporate secrets through dream-sharing is given the inverse task of planting an idea.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/Inception_poster-500x740.jpg",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The lives of two mob hitmen, a boxer, and others intertwine in tales of violence and redemption.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A computer hacker learns the true nature of reality and his role in the war against its controllers.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg",
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/32-500x714.jpeg",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 10,
                            Description = "An insomniac office worker and a soapmaker form an underground fight club that evolves into something more.",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            ReleaseYear = 1999,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Forrest Gump, a man with a low IQ, recounts the early years of his life when he found himself in the middle of key historical events.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/71CHZi4vhWL._SL1500_-500x750.jpg",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Two imprisoned men bond over years, finding solace and redemption through acts of decency.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/the-shawshank-redemption.jpg",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/48-500x741.jpg",
                            ReleaseYear = 2000,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/45-500x743.jpg",
                            ReleaseYear = 1994,
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
                            ImageUrl = "https://api2.zoomg.ir/media/2017-9-f6134586-1165-48cd-82fd-66ddbc25d776-66cc7cff2b5676090d006b91?w=1920&q=80",
                            ReleaseYear = 2017,
                            Title = "Coco"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Greed and class discrimination threaten the symbiotic relationship between a wealthy family and a poor one.",
                            ImageUrl = "https://m.media-amazon.com/images/I/91KArYP03YL._AC_UF894,1000_QL80_.jpg",
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 17,
                            Description = "After the devastating events of Infinity War, the Avengers assemble once more to undo Thanos's actions.",
                            ImageUrl = "https://api2.zoomg.ir/media/2019-7-3170707f-e771-4f73-a721-92061b25df87-66cc7d052b5676090d015469?w=1920&q=80",
                            ReleaseYear = 2019,
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer.",
                            ImageUrl = "https://malltina.com/mag/wp-content/uploads/2019/03/24-1-500x738.jpg",
                            ReleaseYear = 1991,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 19,
                            Description = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/fa/thumb/c/ce/Green_mile.jpg/250px-Green_mile.jpg",
                            ReleaseYear = 1999,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 20,
                            Description = "An insurance salesman discovers his whole life is actually a reality TV show broadcast to the world.",
                            ImageUrl = "https://m.media-amazon.com/images/I/91AJYESZaVL._AC_UF894,1000_QL80_.jpg",
                            ReleaseYear = 1998,
                            Title = "The Truman Show"
                        });
                });

            modelBuilder.Entity("LetterBoxdDomain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("LetterBoxdDomain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LetterBoxdDomain.Comment", b =>
                {
                    b.HasOne("LetterBoxdDomain.Movie", null)
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetterBoxdDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetterBoxdDomain.Rating", b =>
                {
                    b.HasOne("LetterBoxdDomain.Movie", null)
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetterBoxdDomain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LetterBoxdDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetterBoxdDomain.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
